// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDABCaLL0AqpDupz3tgl5JhwyHwBD8w978',
    appId: '1:619698291708:android:883e48b244010eb601a879',
    messagingSenderId: '619698291708',
    projectId: 'gk-sage-admin-cb224',
    storageBucket: 'gk-sage-admin-cb224.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa7D3_LTCL_GcFd5OYeCeP7YbRQLYM4fE',
    appId: '1:619698291708:ios:200eaf5942a29a6e01a879',
    messagingSenderId: '619698291708',
    projectId: 'gk-sage-admin-cb224',
    storageBucket: 'gk-sage-admin-cb224.firebasestorage.app',
    androidClientId:
        '619698291708-meq4r1r4ijmfjo0l9639iik92i9tid7h.apps.googleusercontent.com',
    iosClientId:
        '619698291708-f0nug2m4gjhbfvqedglhsd1fjtn44kpe.apps.googleusercontent.com',
    iosBundleId: 'app.gksage.com',
  );
}
